### ISSUE TITLE
Incapsula Incident - immoweb API

### ISSUE THREAD

**Issue by OKahraman** [hennroja/immowebAPI#1]
Hi Henn -

Looks like Java API can't get the response from immoweb? Do you have the same error message once you try with demochecker?

Here are the details.

http://www.immoweb.be/en/mobile.cfc?method=getResults&xVenteLocation=2&xIdCategorie=5&clientSource=&iphone=&xPrice1=399&xPrice2=700&xCodeCommune1=1000&xCodeCommune2=1040&xCodeCommune3=1050&xmeuble=Y
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=9&xinfo=9-34339873-0 0NNN RT(1454193317640 6) q(0 -1 -1 -1) r(0 -1) B12(4,315,0) U5&incident_id=281000720110133431-341986753782547593&edet=12&cinfo=04000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">

Request unsuccessful. Incapsula incident ID: 281000720110133431-341986753782547593</iframe></body></html>
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

 at [Source: <html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=9&xinfo=9-34339873-0 0NNN RT(1454193317640 6) q(0 -1 -1 -1) r(0 -1) B12(4,315,0) U5&incident_id=281000720110133431-341986753782547593&edet=12&cinfo=04000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 281000720110133431-341986753782547593</iframe></body></html>; line: 1, column: 2]

```
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624)
at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
at de.hennroja.immoweb.api.ImmowebApi.search(ImmowebApi.java:64)
at DemoChecker.main(DemoChecker.java:19)
```

Exception in thread "main" java.lang.NullPointerException
    at DemoChecker.main(DemoChecker.java:32)

**Comment by w0mby** [comment]
You should change the cookie in the ImmowebAPI file.
So go to immoweb with any browser and take your ResponseCookie (at least it's the used term in chrome) and put it in place of the current one (here: connection.addRequestProperty("Cookie","") )
I don't yet think about automatic solution here but at least taking it once is enough after for multiple calls.
